# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, help_text='link from youtube'),
        ),
    ]
