# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160604_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_info',
            field=models.TextField(blank=True, help_text='Full information'),
        ),
    ]
