# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_full_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
