# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='programs',
            field=models.TextField(blank=True, help_text='Programs'),
        ),
    ]
