# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20160902_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_pic', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photo_ava', verbose_name='Photo'),
        ),
    ]
