# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20160902_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
